-- MySQL Script generated by MySQL Workbench
-- Tue Oct 25 21:41:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sistemainstitucional
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistemainstitucional` ;

-- -----------------------------------------------------
-- Schema sistemainstitucional
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistemainstitucional` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `Banco` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Banco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cuenta` (
  `numero` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `id_banco` INT NOT NULL,
  `Nombre_usuario` VARCHAR(45) NOT NULL,
  `Fecha_creacion` VARCHAR(45) NOT NULL,
  `Estado_riesgo` TINYINT(1) NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `id_banco`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Banco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Nombre_usuario_UNIQUE` ON `mydb`.`cuenta` (`Nombre_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta` (
  `numero` INT NOT NULL,
  `numero_cuenta` INT NOT NULL,
  `fecha_vencimiento` INT NOT NULL,
  `cvc` INT NOT NULL,
  `tipo_tarjeta` INT NOT NULL,
  `credito_aprobado` INT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `numero_cuenta`
    FOREIGN KEY ()
    REFERENCES `mydb`.`cuenta` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transaccion` (
  `idtransaccion` INT NOT NULL AUTO_INCREMENT,
  `numero_cuenta_origen` INT NOT NULL,
  `numero_cuenta_destino` INT NOT NULL,
  `id_banco_origen` INT NOT NULL,
  `id_banco_destino` INT NOT NULL,
  `monto` INT NOT NULL,
  `motivo` VARCHAR(200) NULL,
  PRIMARY KEY (`idtransaccion`),
  CONSTRAINT `numero_cuenta_origen`
    FOREIGN KEY ()
    REFERENCES `mydb`.`cuenta` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `numero_cuenta_destino`
    FOREIGN KEY ()
    REFERENCES `mydb`.`cuenta` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_banco_origen`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Banco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_banco_destino`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Banco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oficina` (
  `idoficina` INT NOT NULL,
  PRIMARY KEY (`idoficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`desenbolso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`desenbolso` (
  `idbanco` INT NOT NULL,
  `idoficicina` INT NOT NULL,
  `id_origen` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `motivo` VARCHAR(200) NULL,
  `desenbolsocol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`desenbolsocol`),
  CONSTRAINT `idbanco`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Banco` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idoficicina`
    FOREIGN KEY ()
    REFERENCES `mydb`.`oficina` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sistemainstitucional` ;

-- -----------------------------------------------------
-- Table `sistemainstitucional`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`sedes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`sedes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ciudad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `ciudad` ON `sistemainstitucional`.`sedes` (`ciudad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`oficinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`oficinas` (
  `nombre` VARCHAR(20) NOT NULL,
  `contacto` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `id_sede` INT NOT NULL,
  PRIMARY KEY (`nombre`, `id_sede`),
  CONSTRAINT `oficinas_ibfk_1`
    FOREIGN KEY (`id_sede`)
    REFERENCES `sistemainstitucional`.`sedes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_sede` ON `sistemainstitucional`.`oficinas` (`id_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`desembolsos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`desembolsos` (
  `id_origen` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `motivo` VARCHAR(100) NOT NULL,
  `fecha` DATE NOT NULL,
  `nombre_oficina` VARCHAR(20) NOT NULL,
  `id_sede` INT NOT NULL,
  `id_banco` INT NOT NULL,
  PRIMARY KEY (`nombre_oficina`, `id_sede`, `id_banco`),
  CONSTRAINT `desembolsos_ibfk_1`
    FOREIGN KEY (`nombre_oficina` , `id_sede`)
    REFERENCES `sistemainstitucional`.`oficinas` (`nombre` , `id_sede`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `desembolsos_ibfk_2`
    FOREIGN KEY (`id_banco`)
    REFERENCES `sistemainstitucional`.`bancos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_banco` ON `sistemainstitucional`.`desembolsos` (`id_banco` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `type` ENUM('0', '1') NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `contraseña` VARCHAR(40) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`servicios` (
  `nombre` VARCHAR(50) NOT NULL,
  `valor` FLOAT NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `nombre_oficina` VARCHAR(20) NOT NULL,
  `id_sede` INT NOT NULL,
  PRIMARY KEY (`nombre`, `nombre_oficina`, `id_sede`),
  CONSTRAINT `servicios_ibfk_1`
    FOREIGN KEY (`nombre_oficina` , `id_sede`)
    REFERENCES `sistemainstitucional`.`oficinas` (`nombre` , `id_sede`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `nombre_oficina` ON `sistemainstitucional`.`servicios` (`nombre_oficina` ASC, `id_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`ordenes` (
  `id_orden` INT NOT NULL AUTO_INCREMENT,
  `fecha_generacion` DATE NOT NULL,
  `estado_acceso` TINYINT(1) NOT NULL,
  `fecha_deduccion` DATE NULL DEFAULT NULL,
  `id_persona` INT NOT NULL,
  `nombre_servicio` VARCHAR(50) NOT NULL,
  `nombre_oficina` VARCHAR(20) NOT NULL,
  `id_sede` INT NOT NULL,
  PRIMARY KEY (`id_orden`),
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `sistemainstitucional`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ordenes_ibfk_2`
    FOREIGN KEY (`nombre_servicio` , `nombre_oficina` , `id_sede`)
    REFERENCES `sistemainstitucional`.`servicios` (`nombre` , `nombre_oficina` , `id_sede`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_persona` ON `sistemainstitucional`.`ordenes` (`id_persona` ASC) VISIBLE;

CREATE INDEX `nombre_servicio` ON `sistemainstitucional`.`ordenes` (`nombre_servicio` ASC, `nombre_oficina` ASC, `id_sede` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistemainstitucional`.`trabaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistemainstitucional`.`trabaja` (
  `cargo` VARCHAR(20) NOT NULL,
  `nombre_oficina` VARCHAR(20) NOT NULL,
  `id_sede` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  PRIMARY KEY (`nombre_oficina`, `id_funcionario`),
  CONSTRAINT `trabaja_ibfk_1`
    FOREIGN KEY (`nombre_oficina` , `id_sede`)
    REFERENCES `sistemainstitucional`.`oficinas` (`nombre` , `id_sede`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `trabaja_ibfk_2`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `sistemainstitucional`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `nombre_oficina` ON `sistemainstitucional`.`trabaja` (`nombre_oficina` ASC, `id_sede` ASC) VISIBLE;

CREATE INDEX `id_funcionario` ON `sistemainstitucional`.`trabaja` (`id_funcionario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
